site_name: Target Tracker Help
theme_dir: 'material'
markdown_extensions:
  - admonition
pages: 
  - Welcome: 'index.md'
  - Getting Started:
    - System Requirements: 'getting-started/system-requirements.md'
    - Installing the software: 'getting-started/installation.md'
    - Pupil Selection: 'getting-started/pupil-selection.md'
  - Assessment:
    - EYFS:
      - EYFS Steps Assessment Entry: 'assessment/eyfs/eyfs-steps-assessment-entry.md'
    - Steps:
      - Assessing Without Levels: 'assessment/steps/assessing-without-levels.md'
